version: '2'
services:
  mongo:
    image: mongo:3.4
    networks:
      - unifi
    restart: always
    volumes:
      - /mnt/MEDIA/unifi/db:/data/db
    environment:
      RUNAS_UID0: "false"
      UNIFI_UID: 500
      UNIFI_GID: 100
  controller:
    image: "jacobalberty/unifi:latest"
    depends_on:
      - mongo
    networks:
      - unifi
    restart: always
    volumes:
      - /mnt/MEDIA/unifi/data:/unifi/data
      - /mnt/MEDIA/unifi/log:/unifi/log
      - /mnt/MEDIA/certs/condo.thefairweathers.ca/:/unifi/cert
      - /mnt/MEDIA/unifi/init:/unifi/init.d
    environment:
      DB_URI: mongodb://mongo/unifi
      STATDB_URI: mongodb://mongo/unifi_stat
      DB_NAME: unifi
#      CERT_IS_CHAIN: "true"
#      CERTNAME: fullchain.cer
#      CERT_PRIVATE_NAME: condo.thefairweathers.ca.key
      RUNAS_UID0: "false"
      UNIFI_UID: 500
      UNIFI_GID: 100
    ports:
      - "8080:8080"
      - "8880:8880"
      - "8443:8443"
      - "3478:3478/udp"
      - "10001:10001/udp"
  logs:
    image: bash
    depends_on:
      - controller
    command: bash -c 'tail -f /unifi/log/*'
    restart: always
    volumes:
      - /mnt/MEDIA/unifi/log:/unifi/log

networks:
  unifi:
